name = input("hey whats your name?")
print(f"hey {name}, do you watch sports?")
input()
sport = input("whats your favorite sport to watch?")
print(f"{sport}, I like {sport} too!!")
print(f"who is your favorite athlete in {sport}?")
input()
athlete = input ("who is your favorite athlete in all of the sports")
print(f"I like {athlete} too!! my favorite athlete is lebron James")
print("do you think he will retire?")
print("i dont think he is every going to!")
print("he is the goat")
input()
print("micheal jorden or lebron james")
input
print("its gotta be lebron")